# KoBoToolbox Configuration
KOBO_API_TOKEN = "5723a0f5b9b01dfda17940cd8f1701beb21b6619"
KOBO_ASSET_ID = "aqjgNoL4WiESEEfQ9Sj9DL"
KOBO_MONITORING_ASSET_ID = "aDSNfsXbXygrn8rwKog5Yd"
KOBO_MONITORING_ASSET = "dXdb36aV"
KOBO_ASSET_FORM_CODE = "s8ntxUM5"

# SMTP Configuration
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USERNAME = "okothbasil45@gmail.com"
SMTP_PASSWORD = "eyym rykh nysi bopv"
SMTP_SENDER = "okothbasil45@gmail.com"

# App Configuration
APP_URL = "https://carbontally-iih6rrvvsbzzn3uu8encmz.streamlit.app/"

# Firebase Configuration
FIREBASE_WEB_API_KEY = "AIzaSyABhH4F6H5YL3si18SBZ288orL2TdNsIUM"

[FIREBASE_CONFIG]
type = "service_account"
project_id = "carbontally-42816"
private_key_id = "fb73ae1d08a17e2f8fe0bf7631e2b1ac913aed83"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCP8cp87qBune3L
C7TgktzhAVAYTjX8eNdTKtepb5IeM21b0g9BGtUxfVV5e9i3ISBf6UsB3+lLRgUU
LSQicUS9Qb3+dxDaGRhJK+Dw6tvBmT2pBMXF+NZKc1Vd/67zr0JC9zMHgMa0VqEZ
AI/9sCJAP2iKnIezT1LOizyCozn24EVaKjjBfA9KNqN3TUy7M2XeOeS1c7KPHw03
QgNzR7CzTNOFNOpiGU9J9EW7aSe7JbZiXjHfUjmfTXJryyU0Ds0N5mOtm4Yl9a9B
ues8g/0LndwXcvHsJ0GjoICqzJU10HuFFzbs6KcqnshS37Zx0S2ZoOh6wB1pg2t+
C7B2H3vFAgMBAAECggEAG0jbN3Qp/926scatyfW8nX/YtUq56/nh4tdXmrvVyBi6
bXGzR4V1DNTzizwA97F1SAjaGWheedCzbMAjvc2XmIIqJ95c2OJx2ojRMglqj1dj
OzL25BBHWkRjVZZ+DJ3XYwclapIr2Aolri4PnSgyTdhXEhMam8/448K7vQ2Akr1m
Rr15DgQ9/vM0kCbFjI/KfTMRFgHnPJ6+gJ4xF2/zW2XHttk7ba9XGPqgMSNaqDJk
7PpKR317nsLm6/xbiGyLcestill5BR303eB8AmV+/YqLMv+ZW+l6giXNn0qyGZWN
d1pr6lECl1d/+W8+p/DflGxDPrM8w/0waouWydjlvwKBgQDGsBMpyXqBqF9kjrtR
F7oojr32KiZFhRVyYOS+8IUXXzyZtsHGbuGu1YO1aCRz+Z8LcVjApjkllvU82+bs
84QxZuweg1+NFwkXpPRx4g+s0mE3nnImyFT+oZXNg15s1GRXxp1bI3SL+R23DBrv
KvtL0RQbrQqP9teXxZkWeBOXcwKBgQC5dz7d2bI702CzA/4GffM8hw/mZw245/5u
0m8+W1DmWmB4W9H2HBudcIUGFTpMqh/3ZiF5TkmjYAz/VcWV/bV27hJnGFixR5NP
Nd6biKWESdCsZT6ReAcsgG7hAR0pQCiI6NZsUIn7t9LfsgxWR82t/W7KqT596lIi
OJDon2Qh5wKBgBqfCuJFcZmfwrBJg4WZBUNb5M3v1dLowvfhTaTbuylnhEogN5Rr
1OdFCnGq839qicnRtQ+S9gM4V8GAwU8sTaEE5kwsVAgmdvxpCKudm3YPdiEqpKbX
nrPDWLwBhwxT5OHx5bGJbZs3lKirAYzcGHGPIP+YTtr9OuPGAP4GtrFLAoGBAJuQ
jRfS8TBDNfoSIDHb1XlwpIKS8Cyn03+rXQoF2E7PgdmS0wNHQlaFud6HUbZagKOo
c+1nIFc8SsqlbC1KeLqAKMl233Yb3lDzk3wMWyEiNTlVVuz3q7TFKbvrjkU6foWQ
H8MMryCHaQafNr/sTHZjfFnbKgK92BTCM7IbeAcDAoGAJ4cHhYMuY5WzzLFeSFkT
4ByNOSAtKxDJqV58ZY0E5LLtYplsn5vFYw0mMGW/Y7kbywBVBkYDP0XTBm2AE8tU
/pDvC42jVYDDrgJZUlIKeSux2mCLkIp+jpb2izIge0Zs/fHalRsXx2zEFUe+q9t2
h0J+ORy4qbmwOPHz0jWeF5Y=
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@carbontally-42816.iam.gserviceaccount.com"
client_id = "110815815868868551017"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40carbontally-42816.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
api_key = "AIzaSyABhH4F6H5YL3si18SBZ288orL2TdNsIUM"  # Add api_key here